version: "3"
services:
  appdb:
    build: ./docker/postgres/
    container_name: "sagyo-db"
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/database:/var/lib/postgresql/data